language: node_js
node_js:
  - "6"

branches:  
  only:
    - master

sudo: false

addons:
    code_climate:
        repo_token: $CODE_CLIMATE

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g codecov"
  - "npm install -g codeclimate-test-reporter"

install:
  - npm install

script:
  - npm run test:coverage && codecov
  - npm run test:codeclimate
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: 3blades:ycSapbO8XmfCrdT0vX2yw090
